// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MWYMenu","status":true,"description":"","parameters":{"NeedItem":"true","NeedSkill":"false","NeedEquip":"false","NeedStatus":"false","NeedFormat":"false","VisualRow":"1"}}
];
